### ISSUE TITLE
Rmsprop statistics sharing problem

### ISSUE THREAD

**Issue by pfrendl** [rarilurelo/pytorch_a3c#2]
The rmsprop statistics are created [in the optimizer's step function](https://github.com/rarilurelo/pytorch_a3c/blob/master/async_rmsprop.py#L27), but that is only called after the optimizer is copied into the worker processes. Because of this, all the copies will create separate statistics for themselves and putting these into shared memory. Moving the state initialization into \_\_init__ should work. Not sure if doing it there is good practice though, since all the pytorch optimizer implementations do state initialization in the step function.

Take this with a grain of salt, I am new to PyTorch.

**Comment by pfrendl** [comment]
I did a print check in that if statement, each thread creates separate statistics.

**Comment by rarilurelo** [comment]
Thanks!
I fixed it.
